### ISSUE TITLE
History of operations is not displayed

### ISSUE THREAD

**Issue by FerretRec** [Aureolaworld/aureola#2]

**Comment by FerretRec** [comment]
Remove stub, transactions() was Null
    
      export default {
        name: "history",
        data() {
            return {

            }
        },
        computed:{
          transactions(){
              return this.$store.History.state.data;
          }
        },

**Comment by FerretRec** [comment]
Need to test it

**Comment by Ogorodnikova** [comment]
Test is successful. Closing issue
