### ISSUE TITLE
 It is impossible to attach a document for verification

### ISSUE THREAD

**Issue by FerretRec** [Aureolaworld/aureola#4]

**Comment by FerretRec** [comment]
Allow empty files:

        file_1 = serializers.FileField(required=False, allow_empty_file=True)
        file_2 = serializers.FileField(required=False, allow_empty_file=True)
        file_3 = serializers.FileField(required=False, allow_empty_file=True)
        file_4 = serializers.FileField(required=False, allow_empty_file=True)

Validate files:

        file_main = validated_data.get('file_1')
        file_property = validated_data.get('file_2')
        file_photo = validated_data.get('file_3')
        tx_screen = validated_data.get('file_4')

Create files in the database correctly:

        investor = Investor.objects.create(
            user=user,
            referrer=referrer,
            level=investor_level,
            promo_code=promo_code,
        )

        invesor_files = [
            {'file': file_main, 'type': InvestorFileType.MAIN},
            {'file': file_property, 'type': InvestorFileType.PROPERTY},
            {'file': file_photo, 'type': InvestorFileType.PHOTO},
        ]

        for i in invesor_files:
            try:
                InvestorFile.objects.create(user=investor, **i)
            except Exception as e:
                pass

        Referrer.objects.create(
            user=user,
            promo_code=promo_code,
        )

        payment = ICOPayment.objects.create(
            user=user,
            tx_url=validated_data.get('tx_url'),
            amount=eth_amount,
            # TODO referrer_commission=
            currency=eth_currency,
            eth_amount=eth_amount,
            aur_amount=CurrencyService.convert_amount(eth_amount, eth_currency,
                                                      Currency.objects.get(char_code='AUR')),
            usd_amount=CurrencyService.convert_amount(eth_amount, eth_currency,
                                                      Currency.objects.get(char_code='USD')),
        )

        try:
            PaymentFile.objects.create(
                payment=payment,
                file=tx_screen,
                type=PaymentFileType.TX_SCREEN
            )
         except Exception as e:
            pass

Need to test

**Comment by Ogorodnikova** [comment]
Now it is possible to attach. Bug is fixed.
