### ISSUE TITLE
 Incorrect balance displaying

### ISSUE THREAD

**Issue by FerretRec** [Aureolaworld/aureola#5]

**Comment by FerretRec** [comment]
Minor numbers fix

    @classmethod
    def get_rate_from_aur(cls, convert):
        usd_rate = Rate.objects.filter(currency_sell_id=1, currency_buy_id=2).latest('date')

        if convert.id == 2:
            return usd_rate.amount

        rate_amount = usd_rate.amount
        if convert.char_code == 'ETH':
            eth_usd_rate = Decimal(cls.get_crypto_course('USD', 'ETH'))
            rate_amount = eth_usd_rate * rate_amount

        return round(rate_amount, Currency.objects.get(id=1).decimal_places)

    @classmethod
    def get_rate_to_aur(cls, convert):
        usd_rate = Rate.objects.filter(currency_sell_id=2, currency_buy_id=1).latest('date')

        if convert.id == 2:
            return usd_rate.amount

        rate_amount = usd_rate.amount
        if convert.char_code == 'ETH':
            eth_usd_rate = Decimal(cls.get_crypto_course('ETH', 'USD'))
            rate_amount = eth_usd_rate * rate_amount

        return round(rate_amount, Currency.objects.get(id=1).decimal_places)

**Comment by FerretRec** [comment]
Need to test it

**Comment by Ogorodnikova** [comment]
this bug is fixed
